/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TrabalhadoresRouteImport } from './routes/trabalhadores'
import { Route as LoginRouteImport } from './routes/login'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AgendarIndexRouteImport } from './routes/agendar.index'
import { Route as AgendarClienteRouteImport } from './routes/agendar.cliente'

const TrabalhadoresRoute = TrabalhadoresRouteImport.update({
  id: '/trabalhadores',
  path: '/trabalhadores',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AgendarIndexRoute = AgendarIndexRouteImport.update({
  id: '/agendar/',
  path: '/agendar/',
  getParentRoute: () => rootRouteImport,
} as any)
const AgendarClienteRoute = AgendarClienteRouteImport.update({
  id: '/agendar/cliente',
  path: '/agendar/cliente',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/trabalhadores': typeof TrabalhadoresRoute
  '/agendar/cliente': typeof AgendarClienteRoute
  '/agendar/': typeof AgendarIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/trabalhadores': typeof TrabalhadoresRoute
  '/agendar/cliente': typeof AgendarClienteRoute
  '/agendar': typeof AgendarIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/trabalhadores': typeof TrabalhadoresRoute
  '/agendar/cliente': typeof AgendarClienteRoute
  '/agendar/': typeof AgendarIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/trabalhadores'
    | '/agendar/cliente'
    | '/agendar/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/login' | '/trabalhadores' | '/agendar/cliente' | '/agendar'
  id:
    | '__root__'
    | '/'
    | '/login'
    | '/trabalhadores'
    | '/agendar/cliente'
    | '/agendar/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LoginRoute: typeof LoginRoute
  TrabalhadoresRoute: typeof TrabalhadoresRoute
  AgendarClienteRoute: typeof AgendarClienteRoute
  AgendarIndexRoute: typeof AgendarIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/trabalhadores': {
      id: '/trabalhadores'
      path: '/trabalhadores'
      fullPath: '/trabalhadores'
      preLoaderRoute: typeof TrabalhadoresRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agendar/': {
      id: '/agendar/'
      path: '/agendar'
      fullPath: '/agendar/'
      preLoaderRoute: typeof AgendarIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agendar/cliente': {
      id: '/agendar/cliente'
      path: '/agendar/cliente'
      fullPath: '/agendar/cliente'
      preLoaderRoute: typeof AgendarClienteRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LoginRoute: LoginRoute,
  TrabalhadoresRoute: TrabalhadoresRoute,
  AgendarClienteRoute: AgendarClienteRoute,
  AgendarIndexRoute: AgendarIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
