/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TrabalhadoresRouteImport } from './routes/trabalhadores'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AgendarRouteImport } from './routes/agendar'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AgendarClienteRouteImport } from './routes/agendar.cliente'

const TrabalhadoresRoute = TrabalhadoresRouteImport.update({
  id: '/trabalhadores',
  path: '/trabalhadores',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AgendarRoute = AgendarRouteImport.update({
  id: '/agendar',
  path: '/agendar',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AgendarClienteRoute = AgendarClienteRouteImport.update({
  id: '/cliente',
  path: '/cliente',
  getParentRoute: () => AgendarRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/agendar': typeof AgendarRouteWithChildren
  '/login': typeof LoginRoute
  '/trabalhadores': typeof TrabalhadoresRoute
  '/agendar/cliente': typeof AgendarClienteRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/agendar': typeof AgendarRouteWithChildren
  '/login': typeof LoginRoute
  '/trabalhadores': typeof TrabalhadoresRoute
  '/agendar/cliente': typeof AgendarClienteRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/agendar': typeof AgendarRouteWithChildren
  '/login': typeof LoginRoute
  '/trabalhadores': typeof TrabalhadoresRoute
  '/agendar/cliente': typeof AgendarClienteRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/agendar' | '/login' | '/trabalhadores' | '/agendar/cliente'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/agendar' | '/login' | '/trabalhadores' | '/agendar/cliente'
  id:
    | '__root__'
    | '/'
    | '/agendar'
    | '/login'
    | '/trabalhadores'
    | '/agendar/cliente'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AgendarRoute: typeof AgendarRouteWithChildren
  LoginRoute: typeof LoginRoute
  TrabalhadoresRoute: typeof TrabalhadoresRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/trabalhadores': {
      id: '/trabalhadores'
      path: '/trabalhadores'
      fullPath: '/trabalhadores'
      preLoaderRoute: typeof TrabalhadoresRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agendar': {
      id: '/agendar'
      path: '/agendar'
      fullPath: '/agendar'
      preLoaderRoute: typeof AgendarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agendar/cliente': {
      id: '/agendar/cliente'
      path: '/cliente'
      fullPath: '/agendar/cliente'
      preLoaderRoute: typeof AgendarClienteRouteImport
      parentRoute: typeof AgendarRoute
    }
  }
}

interface AgendarRouteChildren {
  AgendarClienteRoute: typeof AgendarClienteRoute
}

const AgendarRouteChildren: AgendarRouteChildren = {
  AgendarClienteRoute: AgendarClienteRoute,
}

const AgendarRouteWithChildren =
  AgendarRoute._addFileChildren(AgendarRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AgendarRoute: AgendarRouteWithChildren,
  LoginRoute: LoginRoute,
  TrabalhadoresRoute: TrabalhadoresRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
